# Generated by Django 2.2.1 on 2020-05-14 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200514_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimages',
            old_name='image',
            new_name='FILE',
        ),
    ]
