# Generated by Django 2.2.1 on 2020-05-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
